---
- name: Apply common configuration to all Miner nodes
  remote_user: ubuntu
  sudo: true
  hosts: all
  roles:
    - common


- name: Configure and deploy Ethereum
  hosts: tag_Class_Ethereum
  remote_user: ubuntu
  sudo: true
  roles:
    - ethereum
