---
- name: Add Ubuntu SDK Repository
  apt_repository: repo='ppa:ubuntu-sdk-team/ppa' update_cache=yes

- name: Install dependencies with Apt
  apt: pkg={{item}} state=installed
  with_items:
    - libgmp3-dev 
    - libreadline6-dev
    - ubuntu-sdk 
    - qtbase5-private-dev 
    - qtdeclarative5-private-dev 
    - libqt5opengl5-dev
